[package]
name = "sqlformat_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlformat = "0.2.3"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
